import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Documentation — StateZero Labs",
  description:
    "Technical whitepapers, open-source repositories, and pipeline output for StateZero Labs.",
};

const sections = [
  {
    tag: "DOC::WHITEPAPERS",
    title: "Technical Whitepapers",
    description:
      "Peer-reviewed methodology, latent-space architecture diagrams, and full computational validation reports.",
    cards: [
      {
        label: "Platform Architecture v2.1",
        meta: "PDF · June 2026",
        href: "/docs/StateZero_Platform_Documentation.pdf",
        icon: "▤",
        external: false,
      },
      {
        label: "SZ-01 Computational Validation Report",
        meta: "HTML · June 2026",
        href: "/docs/StateZero_Candidate_Report.html",
        icon: "▤",
        external: false,
      },
      {
        label: "LINCS L1000 Ligand Screening Methodology",
        meta: "PDF · May 2026",
        href: "/docs/StateZero_L1000_Methodology.pdf",
        icon: "▤",
        external: false,
      },
    ],
  },
  {
    tag: "DOC::OPEN_SOURCE",
    title: "Open Source Repositories",
    description:
      "Core engine, pipeline orchestration, and utility libraries. All code is MIT-licensed and production-ready.",
    cards: [
      {
        label: "StateZero / core-engine",
        meta: "Python · Nextflow · Active",
        href: "https://github.com/PavelAbramau/StateZero/tree/main/core",
        icon: "⌥",
        external: true,
      },
      {
        label: "StateZero / generator",
        meta: "Python · PyTorch · Active",
        href: "https://github.com/PavelAbramau/StateZero/tree/main/core/generator",
        icon: "⌥",
        external: true,
      },
      {
        label: "StateZero / lincs-screener",
        meta: "Python · Pandas · Active",
        href: "https://github.com/PavelAbramau/StateZero",
        icon: "⌥",
        external: true,
      },
    ],
  },
  {
    tag: "DOC::PIPELINE_OUTPUT",
    title: "Sample Pipeline Output",
    description:
      "Automated candidate dossiers generated by the StateZero engine — structured JSON and annotated PDF exports.",
    cards: [
      {
        label: "SZ-01 Candidate Dossier",
        meta: "JSON · 89% reversal score · June 2026",
        href: "#",
        icon: "{}",
        external: false,
      },
      {
        label: "SZ-01 Annotated Dossier Report",
        meta: "PDF · 4.2 MB · June 2026",
        href: "#",
        icon: "▤",
        external: false,
      },
      {
        label: "CRISPR Knockout Simulation Log",
        meta: "JSON · 12 k lines · June 2026",
        href: "#",
        icon: "{}",
        external: false,
      },
    ],
  },
] as const;

export default function DocumentationPage() {
  return (
    <div className="min-h-screen text-[#F4F4FB]">

      {/* Nav back link */}
      <div className="border-b border-[#334155]">
        <div className="mx-auto max-w-5xl px-6 py-4 flex items-center gap-4">
          <Link
            href="/"
            className="font-mono text-xs uppercase tracking-widest text-[#8D88B3] hover:text-[#22C55E] transition-colors duration-150"
          >
            ← statezero.labs
          </Link>
          <span className="text-[#334155] select-none">/</span>
          <span className="font-mono text-xs uppercase tracking-widest text-[#22C55E]">
            documentation
          </span>
        </div>
      </div>

      {/* Page header */}
      <div className="mx-auto max-w-5xl px-6 pt-16 pb-12 border-b border-[#334155]">
        <p className="font-mono text-xs uppercase tracking-[0.35em] text-[#7C3AED]">
          SYS::DATA_ROOM
        </p>
        <h1 className="mt-4 text-4xl sm:text-5xl font-extrabold tracking-tight text-[#F4F4FB]">
          Documentation &amp; Open Source
        </h1>
        <p className="mt-4 max-w-2xl text-[#8D88B3] text-base leading-relaxed">
          Full technical transparency for investors, collaborators, and the
          scientific community. All artefacts are generated by the StateZero
          computational engine.
        </p>

        {/* Terminal hint */}
        <div className="mt-8 inline-flex items-center gap-3 border border-[#334155] bg-[#06060F] px-4 py-2 rounded-lg font-mono text-xs text-[#22C55E]">
          <span className="text-[#7C3AED]">~ $</span>
          <span>git clone https://github.com/PavelAbramau/StateZero/tree/main/core</span>
        </div>
      </div>

      {/* Sections */}
      <div className="mx-auto max-w-5xl px-6 py-16 space-y-20">
        {sections.map((section) => (
          <div key={section.tag}>

            {/* Section header */}
            <div className="mb-8 flex flex-col gap-1">
              <p className="font-mono text-xs uppercase tracking-[0.35em] text-[#7C3AED]">
                {section.tag}
              </p>
              <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-[#F4F4FB]">
                {section.title}
              </h2>
              <p className="mt-1 max-w-xl text-sm text-[#8D88B3] leading-relaxed">
                {section.description}
              </p>
            </div>

            {/* Card grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {section.cards.map((card) => (
                <a
                  key={card.label}
                  href={card.href}
                  target={card.external || card.href.endsWith(".html") ? "_blank" : undefined}
                  rel={card.external ? "noopener noreferrer" : undefined}
                  download={!card.external && card.href.endsWith(".pdf") ? true : undefined}
                  className="group flex flex-col gap-4 border border-[#334155] bg-[#06060F] p-6 rounded-xl transition-all duration-200 hover:border-[#22C55E] hover:shadow-[0_0_18px_rgba(34,197,94,0.12)]"
                >
                  {/* Icon */}
                  <span className="font-mono text-xl text-[#334155] group-hover:text-[#22C55E] transition-colors duration-200 select-none">
                    {card.icon}
                  </span>

                  {/* Label */}
                  <div className="flex-1">
                    <p className="font-mono text-sm font-semibold text-[#F4F4FB] group-hover:text-[#22C55E] transition-colors duration-200 leading-snug">
                      {card.label}
                    </p>
                    <p className="mt-2 font-mono text-[11px] uppercase tracking-wider text-[#8D88B3]">
                      {card.meta}
                    </p>
                  </div>

                  {/* Arrow */}
                  <span className="font-mono text-xs text-[#334155] group-hover:text-[#22C55E] transition-colors duration-200 self-end">
                    {card.external ? "↗" : "↓"} {card.external ? "open" : "download"}
                  </span>
                </a>
              ))}
            </div>

          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="border-t border-[#334155] mx-auto max-w-5xl px-6 py-8">
        <p className="font-mono text-xs text-[#64748B]">
          StateZero Labs Confidential Data Payload © 2026. All computational
          artefacts generated by the StateZero engine.
        </p>
      </div>

    </div>
  );
}
